# Generated by Django 4.2.23 on 2025-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RnaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation', models.CharField(max_length=7)),
                ('regularization', models.CharField(max_length=7)),
                ('regularization_rate', models.FloatField()),
                ('learning_rate', models.FloatField()),
                ('epochs', models.IntegerField()),
            ],
            options={
                'verbose_name': 'rna_model',
                'verbose_name_plural': 'rna_models',
            },
        ),
    ]
