# Generated by Django 4.2.23 on 2025-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnamodel',
            name='accuracy',
            field=models.FloatField(default=0.9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rnamodel',
            name='batch_size',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rnamodel',
            name='loss',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
