# Generated by Django 4.2.23 on 2025-06-17 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0002_rnamodel_accuracy_rnamodel_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnamodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
