# Generated by Django 4.2.23 on 2025-06-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0003_rnamodel_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ann',
                'verbose_name_plural': 'anns',
            },
        ),
        migrations.CreateModel(
            name='DataParamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField()),
                ('ratio_train', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'data_param',
                'verbose_name_plural': 'data_params',
            },
        ),
        migrations.CreateModel(
            name='HyperparamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation', models.CharField(max_length=7)),
                ('regularization', models.CharField(max_length=7)),
                ('regularization_rate', models.FloatField()),
                ('learning_rate', models.FloatField()),
                ('epochs', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hyperparam',
                'verbose_name_plural': 'hyperparams',
            },
        ),
        migrations.DeleteModel(
            name='RnaModel',
        ),
        migrations.AddField(
            model_name='annmodel',
            name='data_params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnist_app.dataparamsmodel'),
        ),
        migrations.AddField(
            model_name='annmodel',
            name='hyperparams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnist_app.hyperparamsmodel'),
        ),
    ]
