# Generated by Django 4.2.23 on 2025-06-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0004_annmodel_dataparamsmodel_hyperparamsmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyperparamsmodel',
            name='regularization',
        ),
        migrations.RemoveField(
            model_name='hyperparamsmodel',
            name='regularization_rate',
        ),
    ]
