# Generated by Django 4.2.23 on 2025-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0005_remove_hyperparamsmodel_regularization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annmodel',
            name='arquitecture',
            field=models.CharField(default=(784, 10, 10), max_length=12),
            preserve_default=False,
        ),
    ]
