# Generated by Django 4.2.23 on 2025-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0006_annmodel_arquitecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='annmodel',
            name='modelFile',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
