# Generated by Django 4.2.23 on 2025-06-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnist_app', '0007_annmodel_modelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annmodel',
            old_name='modelFile',
            new_name='model_file',
        ),
    ]
